development:
  bucket: TPVPDesa
  access_key_id: AKIAIV3BHRRG6ZYIELWQ
  secret_access_key: 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
test:
  bucket: TiendaPVP
  access_key_id: AKIAIV3BHRRG6ZYIELWQ
  secret_access_key: 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
production:
  bucket: TiendaPVP
  access_key_id: AKIAIV3BHRRG6ZYIELWQ
  secret_access_key: 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